sudo: required

language: node_js
node_js:
  - 'node'
  - '8'

services:
  - docker

script: npm test

jobs:
  include:
    - stage: code quality
      script: npm run coverage:ci
    - script: npm run lint
